trigger:
- main
pool:
  name: Default

variables:
  acrName: arjunacr.azurecr.io
  imageName: petclinic
  tag: $(Build.BuildId)

stages:

# 1️⃣ FETCH SOURCE
- stage: FetchSource
  jobs:
  - job: Checkout
    steps:
    - checkout: self

# 2️⃣ SONARQUBE SCAN
- stage: SonarQube
  jobs:
  - job: Scan
    steps:
    - script: |
        chmod +x mvnw
        ./mvnw clean verify sonar:sonar \
        -Dsonar.projectKey=tsarjun_spring-petclinic \
        -Dsonar.organization=tsarjun \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$(SONAR_TOKEN)

# 3️⃣ MAVEN BUILD
- stage: Build
  jobs:
  - job: MavenBuild
    steps:
    - script: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests

# 4️⃣ DOCKER BUILD + PUSH TO ACR
- stage: DockerBuildPush
  jobs:
  - job: Docker
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'arjun-acr-connection'
        repository: 'petclinic'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

# 5️⃣ TRIVY SCAN
- stage: TrivyScan
  jobs:
  - job: SecurityScan
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release

        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -

        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" \
        | sudo tee -a /etc/apt/sources.list.d/trivy.list

        sudo apt-get update
        sudo apt-get install -y trivy

        trivy image $(acrName)/$(imageName):$(tag)

# 6️⃣ DEPLOY TO AKS (FIXED)
- stage: Deploy
  jobs:
  - job: DeployToAKS
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'aks-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group arjunrg \
            --name arjun-AKS

          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml