trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: arjunacr.azurecr.io
  imageName: petclinic
  tag: latest

stages:

# 1️⃣ Fetch Source
- stage: Fetch
  jobs:
  - job: FetchCode
    steps:
    - checkout: self

# 2️⃣ SonarQube (SonarCloud)
- stage: SonarQube
  jobs:
  - job: Scan
    steps:
    - script: |
        chmod +x mvnw
        ./mvnw clean verify sonar:sonar \
        -Dsonar.projectKey=tsarjun_spring-petclinic \
        -Dsonar.organization=tsarjun \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$(SONAR_TOKEN)

# 3️⃣ Maven Build
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - script: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests

# 4️⃣ Docker Build
- stage: DockerBuild
  jobs:
  - job: BuildImage
    steps:
    - script: |
        docker build -t $(acrName)/$(imageName):$(tag) .

# 5️⃣ Push to ACR
- stage: Push
  jobs:
  - job: PushImage
    steps:
    - script: |
        echo "Logging into ACR"
        docker login $(acrName) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
        docker push $(acrName)/$(imageName):$(tag)

# 6️⃣ Trivy Scan
- stage: Scan
  jobs:
  - job: Security
    steps:
    - script: |
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy
        trivy image $(acrName)/$(imageName):$(tag)

# 7️⃣ Deploy to AKS
- stage: Deploy
  jobs:
  - job: DeployApp
    steps:
    - script: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml