trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: myacr.azurecr.io
  imageName: petclinic
  tag: $(Build.BuildId)

stages:

# 1️⃣ Fetch
- stage: Fetch
  jobs:
  - job: FetchCode
    steps:
    - checkout: self

# 2️⃣ Build (Maven)
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - script: ./mvnw clean package

# 3️⃣ Docker Build
- stage: DockerBuild
  jobs:
  - job: BuildImage
    steps:
    - script: docker build -t $(acrName)/$(imageName):$(tag) .

# 4️⃣ Push to ACR
- stage: Push
  jobs:
  - job: PushImage
    steps:
    - script: |
        az acr login --name myacr
        docker push $(acrName)/$(imageName):$(tag)

# 5️⃣ Trivy Scan
- stage: Scan
  jobs:
  - job: Security
    steps:
    - script: |
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.45.0_Linux-64bit.tar.gz
        tar zxvf trivy_0.45.0_Linux-64bit.tar.gz
        ./trivy image $(acrName)/$(imageName):$(tag)

# 6️⃣ Deploy to AKS
- stage: Deploy
  jobs:
  - job: DeployApp
    steps:
    - script: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
